---
version: '3.2'
services:
  db:
    image: postgres:9.6.3
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB: mta_gtfs
    ports:
      - 5432:5432



  adminer:
    image: adminer
    ports:
      - 8080:8080
...